# Lab 8_3 XOR nn wide deep

In [1]:
import torch

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [3]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [4]:
# nn layers
linear1 = torch.nn.Linear(2, 10, bias=True)
linear2 = torch.nn.Linear(10, 10, bias=True)
linear3 = torch.nn.Linear(10, 10, bias=True)
linear4 = torch.nn.Linear(10, 1, bias=True)
sigmoid = torch.nn.Sigmoid()

In [5]:
# model
model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid, linear3, sigmoid, linear4, sigmoid).to(device)

In [6]:
# define cost/loss & optimizer
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)  # modified learning rate from 0.1 to 1

In [7]:
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)

    # cost/loss function
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 1000 == 0:
        print(step, cost.item())
for name, param in model.named_parameters():
    print(name, param)

0 0.6948983073234558
1000 0.6931379437446594
2000 0.6931172609329224
3000 0.6930763721466064
4000 0.6929103136062622
5000 0.6820826530456543
6000 0.0013025215594097972
7000 0.00048371264711022377
8000 0.00028900461620651186
9000 0.000203805640921928
10000 0.00015652140427846462
0.weight Parameter containing:
tensor([[-1.3068, -0.6912],
        [-0.4730, -0.5731],
        [ 0.8907,  0.9915],
        [ 0.5455,  0.2520],
        [ 4.2752, -2.4747],
        [ 0.0918,  0.8968],
        [-1.3766,  2.9233],
        [ 5.3368,  5.3779],
        [ 1.7273, -3.1492],
        [ 1.3786,  1.4404]], requires_grad=True)
0.bias Parameter containing:
tensor([ 1.0628, -0.3164, -1.0381, -0.7047,  0.9445,  0.1699,  0.5979, -1.7873,
        -0.8449, -2.0285], requires_grad=True)
2.weight Parameter containing:
tensor([[-0.0255,  0.0708, -0.2011,  0.1645, -0.6262,  0.1004, -0.1564,  0.4924,
          0.2369, -0.3744],
        [-0.5618, -0.2137,  0.4969,  0.4157,  0.4048, -0.1931,  0.3538, -0.9960,
         -0.

In [8]:
# Accuracy computation
# True if hypothesis>0.5 else False
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('\nHypothesis: ', hypothesis.detach().cpu().numpy(), '\nCorrect: ', predicted.detach().cpu().numpy(), '\nAccuracy: ', accuracy.item())


Hypothesis:  [[1.1170164e-04]
 [9.9982882e-01]
 [9.9984229e-01]
 [1.8536496e-04]] 
Correct:  [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0
