# Lab 8_2: Improved XOR nn implementation

In [1]:
import torch

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [3]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

Add a linear layer to enhance the model.

In [4]:
# nn layers
linear1 = torch.nn.Linear(2, 2, bias=True)
linear2 = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()

In [5]:
# model
model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid).to(device)

In [6]:
# define cost/loss & optimizer
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)  # modified learning rate from 0.1 to 1

In [7]:
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)

    # cost/loss function
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 1000 == 0:
        print(step, cost.item())
for name, param in model.named_parameters():
    print(name, param)

0 0.7434073090553284
1000 0.6930999755859375
2000 0.6838315725326538
3000 0.013983804732561111
4000 0.005768367554992437
5000 0.0036007282324135303
6000 0.002609650371596217
7000 0.0020436225458979607
8000 0.0016780965961515903
9000 0.001422818168066442
10000 0.0012345178984105587
0.weight Parameter containing:
tensor([[-6.5538, -6.5538],
        [-7.3489, -7.3487]], requires_grad=True)
0.bias Parameter containing:
tensor([9.7932, 3.1656], requires_grad=True)
2.weight Parameter containing:
tensor([[ 14.4861, -15.0305]], requires_grad=True)
2.bias Parameter containing:
tensor([-6.9082], requires_grad=True)


In [8]:
# Accuracy computation
# True if hypothesis>0.5 else False
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('\nHypothesis: ', hypothesis.detach().cpu().numpy(), '\nCorrect: ', predicted.detach().cpu().numpy(), '\nAccuracy: ', accuracy.item())


Hypothesis:  [[0.00106364]
 [0.99889404]
 [0.99889404]
 [0.00165861]] 
Correct:  [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0
